# DataSource Config
# _Ww350702
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql8.0+
    url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: _Ww350702
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8080

shiro-redis:
  enabled: true
  redis-manager:
    host: localhost:6379

bjergsen:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization

# java.io.FileNotFoundException: class path resource [templates/]
# cannot be resolved to absolute file path because it does not reside in the file system:
# jar:file:/tmp/vueblog-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/mybatis-plus-generator-3.2.0.jar!/templates/
# debug: true
